- name: Installing gnupg2
  become: yes
  become_user: root
  become_method: sudo
  apt:
    pkg:
      - gnupg2
    state: latest
    update_cache: true

- name: Add repository
  become: yes
  become_user: root
  become_method: sudo
  shell: sh -c 'echo "deb http://deb.anydesk.com/ all main" > /etc/apt/sources.list.d/anydesk.list'

- name: Download apt key
  become: yes
  become_user: root
  become_method: sudo
  get_url:
    url: https://keys.anydesk.com/repos/DEB-GPG-KEY
    dest: /tmp

- name: Add a key from a file
  become: yes
  become_user: root
  become_method: sudo
  apt_key:
    file: /tmp/DEB-GPG-KEY
    state: present

- name: Installing anydesk
  become: yes
  become_user: root
  become_method: sudo
  apt:
    pkg:
      - anydesk
    update_cache: true