- name: Add php apt key
  become: yes
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x4F4EA0AAE5267A6C
    state: present

- name: Add repository
  become: yes
  apt_repository:
    repo: "deb http://ppa.launchpad.net/ondrej/php/ubuntu focal main"
    state: present
    update_cache: yes

#TODO: Solve problem installing libssl library cause it is deprecated
- name: Install PHP
  become: yes
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
      - zip
      - imagemagick
      - sqlite3
      - "php{{ PHP_VERSION }}-sqlite3"
      - "php{{ PHP_VERSION }}-cli"
      - "php{{ PHP_VERSION }}-bcmath"
      - "php{{ PHP_VERSION }}-mbstring"
      - "php{{ PHP_VERSION }}-curl"
      - "php{{ PHP_VERSION }}-gmp"
      - "php{{ PHP_VERSION }}-xml"
      - "php{{ PHP_VERSION }}-mysql"
      - "php{{ PHP_VERSION }}-zip"
      - "php{{ PHP_VERSION }}-imagick"
      - "php{{ PHP_VERSION }}-intl"
      - "php{{ PHP_VERSION }}-xdebug"

- name: Enable cli opcache
  become: yes
  lineinfile:
    path: "/etc/php/{{ PHP_VERSION }}/cli/conf.d/10-opcache.ini"
    line: opcache.enable_cli = 1

- name: Install composer
  become: yes
  get_url:
    url: https://getcomposer.org/download/1.10.22/composer.phar
    dest: /usr/sbin/composer
    checksum: sha256:6127ae192d3b56cd6758c7c72fe2ac6868ecc835dae1451a004aca10ab1e0700
    mode: 0555

- lineinfile:
    path: "{{ item }}"
    line: "export PATH=~/.config/composer/vendor/bin:$PATH"
  with_items:
    - ~/.bashrc