# This file contains the steps flags to determine which steps yo want to
# execute with the command make configure-linux, feel free to change this
# variable values according to your needs
# 
# Possible values por each variable:
# - false
# - true

AWS_CLI_ENABLED: false

LINUX_UTILITIES_ENABLED: false

ZSH_AND_POWER10K_THEME_ENABLED: false

VIM_THEME_AND_SETTINGS_ENABLED: false

# PROGRAMMING LANGUAGES

GOLANG_ENABLED: false

NODEJS_ENABLED: false

PHP_ENABLED: false

PYTHON_ENABLED: true

# CODE EDITORS

VISUAL_STUDIO_CODE_ENABLED: false

VISUAL_STUDIO_CODE_THEME_AND_EXTENSIONS_ENABLED: false

## BROWSERS

GOOGLE_CHROME_ENABLED: false

BRAVE_BROWSER_ENABLED: false

## EXTRA SOFTWARE

SPOTIFY_ENABLED: true

DBEAVER_ENABLED: true

SLACK_ENABLED: true

DISCORD_ENABLED: true

ANYDESK_ENABLED: true

## LOCAL DEVELOPMENT TOOLS

NGINX_ENABLED: true

MYSQL_ENABLED: true







