- hosts: localhost

  vars_files:
    - ../configuration.yml

  vars: 
    LIBRARY_NAME:
      - boto3==1.16.25
      - boto==2.49.0
      - requests==2.25.0
    
  tasks:
    - name: Install python3 libs
      pip:
        name: "{{LIBRARY_NAME}}"
