- hosts: localhost

  vars_files:
    - ../configuration.yml

  tasks:
  - name: Remove snapd restriction
    become: yes
    shell: mv /etc/apt/preferences.d/nosnap.pref /nosnap.backup

  - name: Installing packages
    become: yes
    become_user: root
    become_method: sudo
    apt:
      pkg:
        - vim
        - htop
        - mysql-client
        - xclip
        - git
        - net-tools
        - tree
        - zsh
        - snapd
      state: latest
      update_cache: true

  - name: Create .vim folder structure
    file:
        path: "{{ item }}"
        state: directory
    loop:
      - ~/.vim
      - ~/.vim/autoload
      - ~/.vim/backup
      - ~/.vim/colors
      - ~/.vim/plugged

  - name: Install vim pluggin manager
    get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.vim/autoload/plug.vim

  - name: Download color scheme molokai
    get_url:
        url: https://raw.githubusercontent.com/tomasr/molokai/master/colors/molokai.vim
        dest: ~/.vim/colors/molokai.vim

  - name: Configure vimrc
    shell: cp templates/vimrc_template.txt ~/.vimrc

  - name: Create fonts folder
    file:
        path: ~/.local/share/fonts
        state: directory

  - name: Install fonts
    get_url:
        url: "{{ item }}"
        dest: ~/.local/share/fonts 
    loop:
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
        - https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf

  - name: Reload fonts
    shell: fc-cache -f -v

  - name: Remove prevous configuration file
    file:
        path: ~/.oh-my-zsh
        state: absent

  - name: Install Oh my zsh
    shell: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"  

  - name: Clone power10k repository
    git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: ~/powerlevel10k
  
  - name: Append source in zshrc
    lineinfile:
        insertbefore: BOF
        path: ~/.zshrc
        line: source ~/powerlevel10k/powerlevel10k.zsh-theme

  - name: Set p10k configurations
    shell: cp templates/p10k_configuration.txt ~/.p10k.zsh

  - name: Disable p10k wizzard
    lineinfile:
        insertbefore: BOF
        path: ~/.zshrc 
        line: POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true

  - name: Load p10k configurations
    lineinfile:
        insertbefore: BOF
        path: ~/.zshrc 
        line: source ~/.p10k.zsh

  - name: Set zsh as a default shell
    lineinfile:
        path: ~/.bashrc 
        line: /bin/zsh
