- hosts: localhost

  vars_files:
    - ../configuration.yml

  tasks:
  - name: installing packages
    become: yes
    apt:
      pkg:
        - vim
        - htop
        - mysql-client
        - xclip
        - git
        - net-tools
        - tree
      state: latest
      update_cache: true
