- hosts: localhost

  vars_files:
    - ../configuration.yml

  tasks:
  - package:
      name:
        - vim
        - htop
        - mysql-client
        - xclip
        - git
        - netstat
        - tree

  - name: sysctl
    sysctl:
      name: fs.inotify.max_user_watches
      value: '524288'
      state: present
    when: LINUX_UTILITIES_ENABLED
