- hosts: localhost

  vars_files:
    - ../configuration.yml

  tasks:
    - name: update package index
      become: yes
      become_user: root
      become_method: sudo
      apt:
        pkg:
          - software-properties-common
          - apt-transport-https
          - wget
        update_cache: true
