- hosts: localhost
  connection: local

  vars_files:
      - ../configuration.yml

  tasks:
      - name: Check configuration file
        meta: end_play
        when: not GOOGLE_CHROME_ENABLED

      - name: Install google chrome
        become: yes
        apt:
          deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb