- hosts: localhost

  vars_files:
    - ../configuration.yml

  tasks:
    - name: Install google chrome
      become: yes
      apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb