- hosts: localhost

  vars_files:
    - ../configuration.yml

  tasks:
    - name: install brave browser
      become: yes
      get_url: 
          url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
          dest: /usr/share/keyrings/

    - name: add brave repository
      become: yes
      become_user: root
      become_method: sudo
      apt_repository:
          repo: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
          state: present

    - name: install brave
      become: yes
      apt:
          name: brave-browser
          state: present
          update_cache: yes