- hosts: localhost
  connection: local

  vars_files:
      - ../configuration.yml

  tasks:
      - name: Check configuration file
        meta: end_play
        when: not DB_BEAVER_ENABLED

      - name: Install DbBeaver
        become: yes
        apt:
          deb: https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb