- hosts: localhost
  connection: local

  vars_files:
    - ../configuration.yml

  tasks:
    - name: Install "slack
      become: yes
      snap:
        name: slack
        classic: yes
        channel: stable