- hosts: localhost
  connection: local

  vars_files:
      - ../configuration.yml

  tasks:
      - name: Check configuration file
        meta: end_play
        when: not NGINX_ENABLED

      - name: Installing packages
        become: yes
        become_user: root
        become_method: sudo
        apt:
          pkg:
            - nginx
          state: latest
          update_cache: true