- hosts: localhost
  connection: local

  vars_files:
      - ../configuration.yml

  tasks:
      - name: Check configuration file
        meta: end_play
        when: not DISCORD_ENABLED

      - name: Install discord
        become: yes
        snap:
          name: discord
          classic: yes
          channel: stable